// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdvKDrwqIDXok9v-wJWzd7d9KFnIOh8ug',
    appId: '1:395265015249:web:b1d1f64fad3528cc5af4f0',
    messagingSenderId: '395265015249',
    projectId: 'gotham-a59dc',
    authDomain: 'gotham-a59dc.firebaseapp.com',
    storageBucket: 'gotham-a59dc.appspot.com',
    measurementId: 'G-RV6P3TBR7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpR3N5pTfdUcK6ziNj0XhFyo1XJHzFfOo',
    appId: '1:395265015249:android:c773c8743cf01f545af4f0',
    messagingSenderId: '395265015249',
    projectId: 'gotham-a59dc',
    storageBucket: 'gotham-a59dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASNbn9-O9Otx_dC7CKJqyXuSUCzHYAyDg',
    appId: '1:395265015249:ios:531748d787223d825af4f0',
    messagingSenderId: '395265015249',
    projectId: 'gotham-a59dc',
    storageBucket: 'gotham-a59dc.appspot.com',
    iosBundleId: 'com.example.gothamCoderWork',
  );
}
